### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [mjwalavich/prj-rev-bwfs-dasmoto#6]
**GRADE**: Needs Improvement

**SUMMARY**: Good start on this project! With a could small tweaks to the font-family for the page, the site will be looking great. Excellent work keeping the css neat and organized and great job using divs, classes, and ids to help structure the html. 

Behind the scenes in the html, make sure to use the alt attribute on your img elements to ensure a wider variety of users have access to the information being presented by the images. Also, try to keep your indentation / spacing as consistent as possible throughout the html. Clean, concise code is crucial and only becomes more so as your projects grow in size and complexity.

As a next step try saving your image files locally to your resources folder and then using relative file paths to link to those from your html and css. The link to css on line 5 of your html is a great example and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Keep up the good work!

**Comment by mjwalavich** [comment]
Thank you for the feedback!  I kind of fell behind in the class due to Hurricane Irma.  I had to evacuate for 10 days and I have been trying to get back on schedule with the program.
